from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

import numpy as np
import torch
from PIL import Image
from diffusers import DDIMScheduler, DiffusionPipeline


def main() -> int:
    parser = argparse.ArgumentParser(description="Run official SFWMark detection for one generated website image.")
    parser.add_argument("--job-id", required=True)
    parser.add_argument("--source-job-id", required=True)
    parser.add_argument("--image-path", required=True)
    parser.add_argument("--analysis-mode", choices=["verify", "identify"], default="verify")
    parser.add_argument("--project-root", default=str(Path(__file__).resolve().parents[3]))
    args = parser.parse_args()

    project_root = Path(args.project_root).resolve()
    sfw_dir = configured_repo(project_root)
    src_dir = sfw_dir / "src"
    if not (src_dir / "utils.py").is_file():
        print(f"SFWMark repo not found at {sfw_dir}", file=sys.stderr)
        print("Run: bash backend/integrations/sfwmark/setup_sfwmark.sh", file=sys.stderr)
        return 2

    source_dir = project_root / "backend" / "storage" / "outputs" / args.source_job_id
    metadata_path = source_dir / "metadata.json"
    pattern_path = source_dir / "pattern_list-2048.pt"
    identify_path = source_dir / "identify_gt_indices_1.npy"
    if not metadata_path.is_file() or not pattern_path.is_file() or not identify_path.is_file():
        print(f"Missing SFWMark generation artifacts in {source_dir}", file=sys.stderr)
        print("Detection currently requires an image generated by this website run.", file=sys.stderr)
        return 3

    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    wm_type = metadata.get("wm_type", "HSQR")
    if wm_type not in {"HSTR", "HSQR"}:
        print(f"Unsupported SFWMark watermark type in metadata: {wm_type}", file=sys.stderr)
        return 4
    model_id = os.environ.get("SFW_MODEL_ID", metadata.get("model_id", "sd2-community/stable-diffusion-2-1-base"))

    sys.path.insert(0, str(src_dir))
    import utils as sfw_utils  # type: ignore

    torch_dtype = torch.float32
    pipe = DiffusionPipeline.from_pretrained(model_id, torch_dtype=torch_dtype)
    pipe.scheduler = DDIMScheduler.from_config(pipe.scheduler.config)
    pipe = pipe.to(sfw_utils.device)
    pipe.set_progress_bar_config(disable=True)

    image = Image.open(args.image_path).convert("RGB").resize((512, 512))
    with torch.no_grad():
        inverted = sfw_utils.ddim_invert(pipe, [image], invert_guidance=0).cpu()
        target_fft = torch.zeros_like(inverted, dtype=torch.complex64)
        target_fft[sfw_utils.center_slice] = sfw_utils.fft(inverted[sfw_utils.center_slice])

        pattern_list = torch.load(pattern_path, map_location="cpu").cpu()
        identify_gt_indices = np.load(identify_path)
        if pattern_list.ndim < 1 or len(pattern_list) == 0:
            raise ValueError("SFWMark pattern bank is empty")
        if identify_gt_indices.size == 0:
            raise ValueError("SFWMark ground-truth index file is empty")
        key_index = int(identify_gt_indices[0])
        if not 0 <= key_index < len(pattern_list):
            raise ValueError(f"SFWMark ground-truth key index {key_index} is outside the pattern bank")
        pattern_gt = pattern_list[key_index].cpu()

        if wm_type == "HSQR":
            distance = sfw_utils.get_distance_hsqr(
                pattern_gt,
                target_fft,
                channel=sfw_utils.HSQR_WATERMARK_CHANNEL,
                p=1,
                center=True,
            )
            candidate_distances = [
                sfw_utils.get_distance_hsqr(
                    candidate,
                    target_fft,
                    channel=sfw_utils.HSQR_WATERMARK_CHANNEL,
                    p=1,
                    center=True,
                )
                for candidate in pattern_list
            ]
        else:
            mask = sfw_utils.watermark_region_mask_hstr.cpu()
            distance = sfw_utils.get_distance(
                pattern_gt,
                target_fft,
                mask=mask,
                channel=sfw_utils.RINGID_WATERMARK_CHANNEL,
                p=1,
                mode="complex",
                channel_min=True,
                center=True,
            )
            candidate_distances = [
                sfw_utils.get_distance(
                    candidate,
                    target_fft,
                    mask=mask,
                    channel=sfw_utils.RINGID_WATERMARK_CHANNEL,
                    p=1,
                    mode="complex",
                    channel_min=True,
                    center=True,
                )
                for candidate in pattern_list
            ]

    distances_np = np.array(candidate_distances, dtype=np.float64)
    predicted_index = int(np.argmin(distances_np))
    sorted_distances = np.sort(distances_np)
    best_distance = float(sorted_distances[0])
    second_best_distance = float(sorted_distances[1]) if len(sorted_distances) > 1 else best_distance
    margin = max(0.0, second_best_distance - best_distance)
    identified = predicted_index == key_index
    score = 100 if identified else 0

    result = {
        "runner": "official-sfwmark-single-detect",
        "analysis_mode": args.analysis_mode,
        "wm_type": wm_type,
        "model_id": model_id,
        "source_job_id": args.source_job_id,
        "image_path": str(args.image_path),
        "key_index": key_index,
        "predicted_index": predicted_index,
        "identified": identified,
        "matched": identified,
        "verification_distance": float(distance),
        "distance": float(distance),
        "best_distance": best_distance,
        "second_best_distance": second_best_distance,
        "margin": margin,
        "score": score,
    }

    job_dir = project_root / "backend" / "storage" / "outputs" / args.job_id
    job_dir.mkdir(parents=True, exist_ok=True)
    (job_dir / "detect.json").write_text(json.dumps(result, indent=2), encoding="utf-8")
    print(json.dumps(result, indent=2))
    return 0


def configured_repo(project_root: Path) -> Path:
    configured = os.environ.get("SFWMARK_REPO")
    if configured:
        return Path(configured).resolve()
    checked_in = project_root / "work" / "repos" / "SFWMark"
    return checked_in if checked_in.is_dir() else (project_root / "external" / "SFWMark").resolve()


if __name__ == "__main__":
    raise SystemExit(main())
